name: "Standard workflow"
description: "Adds GitHub runner IP, runs tests, deploys to Cloud Run, and removes IP"
inputs:
  project_id:
    description: "GCP Project ID"
    required: true
  service_name:
    description: "Service name for Cloud Run"
    required: true
  action_url:
    description: "Base URL for IP management API"
    required: true
  run_tests:
    description: "Should it run Python tests?"
    required: true
  run_command:
    description: "build command"
    required: False

runs:
  using: "composite"
  steps:
    - name: Add IP to whitelist
      uses: Mariolaus/open_actions/.github/actions/add_worker_ip@main
      with:
        ip: ${{ steps.get_ip.outputs.ip }}
        url: "${{ inputs.action_url }}/add_ip?ip="
      env:
        credentials_json: '${{ env.GCP_BUILD_AND_DEPLOY_PROD }}'

    - name: Run Tests
      if: ${{ inputs.run_tests == 'true' }}
      uses: Mariolaus/open_actions/.github/actions/run_tests@main
      env:
        READ_ALL_REPOS_TOKEN: ${{ env.READ_ALL_REPOS_TOKEN }}
        GCP_BUILD_AND_DEPLOY_PROD: '${{ env.GCP_BUILD_AND_DEPLOY_PROD }}'

    - name: Build and Deploy to Cloud Run
      if: ${{ github.ref == 'refs/heads/PROD' }}
      uses: Mariolaus/open_actions/.github/actions/build_image_and_deploy_to_cloud_run@main
      with:
        PROJECT_ID: ${{ inputs.project_id }}
        SERVICE: ${{ inputs.service_name }}
        run_command: ${{ inputs.run_command }}
      env:
        DEVOPS_MICROVM_RSA: ${{ env.DEVOPS_MICROVM_RSA }}
        READ_ALL_REPOS_TOKEN: ${{ env.READ_ALL_REPOS_TOKEN }}
        DEVOPS_GCLOUD_CREDENTIALS: ${{ env.DEVOPS_GCLOUD_CREDENTIALS }}
        GCP_BUILD_AND_DEPLOY_PROD: '${{ env.GCP_BUILD_AND_DEPLOY_PROD }}'

    - name: Remove IP from whitelist
      if: always()
      uses: Mariolaus/open_actions/.github/actions/delete_worker_ip@main
      with:
        github_id: "${{ steps.add_ip.outputs.github_id }}"
        credentials_json: '${{ env.GCP_BUILD_AND_DEPLOY_PROD }}'
        url: "${{ inputs.action_url }}/delete_ip?github_id="
