# .github/actions/add_worker_ip/action.yml

name: "Add GitHub Worker IP to Whitelist"
description: "Adds the GitHub Actions runner IP to an authorized IP list"
inputs:
  ip:
    description: "IP address to add to the whitelist"
    required: true
  url:
    description: "IP address to add to the whitelist"
    required: true

outputs:
  github_id:
    description: "The GitHub ID returned from the API"
    value: ${{ steps.add_ip_step.outputs.github_id  }}

runs:
  using: "composite"
  steps:
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.credentials_json }}

    - name: Add GitHub Worker IP to Authorized IPs
      id: add_ip_step
      run: |
        ID_TOKEN=$(gcloud auth print-identity-token)
        github_id=$(curl -H "Authorization: Bearer ${ID_TOKEN}" "${{ secrets.DEVOPS_ENDPOINT }}${{ inputs.ip }}")
        github_id=$(echo "$github_id" | jq -r '.output')
        echo "github_id=${github_id}" >> $GITHUB_OUTPUT
      shell: bash