name: "Build Image And Deploy to Cloud Run"
description: ""
inputs:
  PROJECT_ID:
    description: "Gcloud project ID"
    required: true
  SERVICE:
    description: "Cloud Run service name"
    required: true
  REGION:
    description: "Gcloud Region"
    required: true
    default: "europe-west8"
  run_command:
    description: "Docker build command"
    required: true

runs:
  using: "composite"
  steps:

    # Checkout repo
    - name: Check out the repository
      uses: actions/checkout@v3

    # Create a new Git tag
    - name: Create Git Tag
      id: create_tag
      run: |
        TAG="v$(date +'%Y-%m-%d-%H%M')"
        echo "GIT_TAG=$TAG" >> $GITHUB_ENV   #${{ env.GIT_TAG }}
      shell: bash

    - name: Tag snapshot
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ env.READ_ALL_REPOS_TOKEN }}
        tag: ${{ env.GIT_TAG }}

    #Authenticate in Google
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GCP_BUILD_AND_DEPLOY }}

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Derive service account ID
      id: derive_sa
      shell: bash
      run: |
        # sanitize the Cloud Run service name
        SERVICE_NAME=$(echo "${{ inputs.SERVICE }}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
        SA_ID="run-${SERVICE_NAME}"
        # GCP limits service account ID to max 30 chars
        SA_ID=${SA_ID:0:30}
        echo "service_account_id=$SA_ID" >> $GITHUB_OUTPUT

    - name: Check if service account exists
      id: sa_check
      shell: bash
      run: |
        SA_EMAIL="${{ steps.derive_sa.outputs.service_account_id }}@${{ inputs.gcp_project }}.iam.gserviceaccount.com"
        if gcloud iam service-accounts describe "$SA_EMAIL" &>/dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create service account
      if: steps.sa_check.outputs.exists == 'false'
      shell: bash
      run: |
        gcloud iam service-accounts create "${{ steps.derive_sa.outputs.service_account_id }}" \
          --description="Service account for Cloud Run and Secrets" \
          --display-name="GitHub Action Service Account"

    - name: Grant Cloud Run invoke permission
      shell: bash
      run: |
        SERVICE_EMAIL="${{ steps.derive_sa.outputs.service_account_id }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
        gcloud run services add-iam-policy-binding "${{ inputs.SERVICE }}" \
          --region="${{ inputs.REGION }}" \
          --member="serviceAccount:$SERVICE_EMAIL" \
          --role="roles/run.invoker"

    - name: Grant Secret Manager access
      shell: bash
      run: |
        SERVICE_EMAIL="${{ steps.derive_sa.outputs.service_account_id }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
        IFS=',' read -ra SECRETS <<< "a, b"
        for SECRET in "${SECRETS[@]}"; do
          gcloud secrets add-iam-policy-binding "$SECRET" \
            --member="serviceAccount:$SERVICE_EMAIL" \
            --role="roles/secretmanager.secretAccessor"
        done

    # Docker configuration
    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker ${{ inputs.REGION }}-docker.pkg.dev --quiet
      shell: bash

    # check if repository exists
    - name: Check if Artifact Registry Repository Exists
      id: check_repo
      run: |
        # Check if the repository exists by trying to describe it
        response=$(gcloud artifacts repositories describe ${{ inputs.SERVICE }} --location=${{ inputs.REGION }} --format="value(name)" || echo "not_found")
        if [ "$response" == "not_found" ]; then
          echo "Repository does not exist. Proceeding with creation."
          echo "create_repo=true" >> $GITHUB_ENV
        else
          echo "Repository already exists."
          echo "create_repo=false" >> $GITHUB_ENV
        fi
      shell: bash

    # create repository if it does not exist
    - name: Create Artifact Registry Repository
      if: env.create_repo == 'true'
      run: |
        gcloud artifacts repositories create ${{ inputs.SERVICE }} \
          --repository-format=Docker \
          --location=${{ inputs.REGION }} \
          --description="Docker repository for ${{ inputs.SERVICE }} project"
      shell: bash

    # Build Image
    - id: build_image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        image_id="${{ inputs.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.SERVICE }}/${{ inputs.SERVICE }}:${{ env.GIT_TAG }}"
        ${{ inputs.run_command }}
        echo "image_id=$image_id" >> $GITHUB_OUTPUT
      shell: bash

    # Push image in Artifact Registry
    - name: Push Docker Image to Artifact Registry
      run: |
        docker push "${{ steps.build_image.outputs.image_id }}"
      shell: bash

    # Deploy on Cloud Run
    - name: Deploy to Cloud Run
      id: deploy_cr
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ inputs.SERVICE }}
        region: ${{ inputs.REGION }}
        image: "${{ steps.build_image.outputs.image_id }}"
        tag: "${{ env.GIT_TAG }}"
        service_account: "{{ steps.derive_sa.outputs.service_account_id }}"
        env_vars: |
          PROJECT_ID=${{ env.PROJECT_ID }}