name: "Build Image And Deploy to Cloud Run"
description: ""
inputs:
  PROJECT_ID:
    description: "Gcloud project ID"
    required: true
  SERVICE:
    description: "Cloud Run service name"
    required: true
  REGION:
    description: "Gcloud Region"
    required: true
    default: "europe-west8"
  run_command:
    description: "Docker build command"
    required: true

runs:
  using: "composite"
  steps:

    #Authenticate in Google
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.credentials_json }}

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.PROJECT_ID }}

    # Docker configuration
    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker ${{ inputs.REGION }}-docker.pkg.dev --quiet
      shell: bash

    # Build Image
    - id: build_image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        image_id="${{ inputs.REGION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE }}/${{ inputs.SERVICE }}:${{ github.sha }}"
        ${{ inputs.run_command }}
        echo "image_id=$image_id" >> $GITHUB_OUTPUT
      shell: bash

    # Push image in Artifact Registry
    - name: Push Docker Image to Artifact Registry
      run: |
        docker push "${{ steps.build_image.outputs.image_id }}"
      shell: bash

    # Deploy su Cloud Run
    - name: Deploy to Cloud Run
      id: deploy_cr
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ inputs.SERVICE }}
        region: ${{ inputs.REGION }}
        image: "${{ steps.build_image.outputs.image_id }}"