name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      project_id:
        description: "GCP Project ID"
        required: true
        type: string
      service_name:
        description: "Service name for Cloud Run"
        required: true
        type: string
      action_url:
        description: "Base URL for IP management API"
        required: true
        type: string

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Add IP to whitelist
      - name: Enable Github worker IP
        id: add_ip
        uses: Mariolaus/open_actions/.github/actions/add_worker_ip@main
        env:
          credentials_json: '${{ secrets.GCP_BUILD_AND_DEPLOY_PROD }}'
        with:
          ip: $(curl ifconfig.me)
          url: "${{ inputs.action_url }}/add_ip?ip="

      # Build image and deploy to Cloud Run if we are on branch PROD only
      - name: Build image and Deploy to Cloud Run
        if: github.ref == 'refs/heads/PROD' # or UAT, then add the branch name to the service todo
        uses: Mariolaus/open_actions/.github/actions/build_image_and_deploy_to_cloud_run@main
        env:
          DEVOPS_MICROVM_RSA: ${{ secrets.DEVOPS_MICROVM_RSA }}
          READ_ALL_REPOS_TOKEN: ${{ secrets.READ_ALL_REPOS_TOKEN }}
          DEVOPS_GCLOUD_CREDENTIALS: ${{ secrets.DEVOPS_GCLOUD_CREDENTIALS }}
          credentials_json: '${{ secrets.GCP_BUILD_AND_DEPLOY_PROD }}'
        with:
          PROJECT_ID: ${{ inputs.project_id }}
          SERVICE: ${{ inputs.service_name }}
          run_command: |
            echo "${{ env.DEVOPS_MICROVM_RSA }}" > gcp_run_ssh_rsa_key
            echo "${{ env.READ_ALL_REPOS_TOKEN }}" > read_all_repos_token
            echo "${{ env.DEVOPS_GCLOUD_CREDENTIALS }}" > gcloud_credentials
            docker build \
              --secret id=GCP_RUN_SSH_RSA_KEY,src=gcp_run_ssh_rsa_key \
              --secret id=READ_ALL_REPOS_TOKEN,src=read_all_repos_token \
              --secret id=GCP_RUN_SSH_GCLOUD_CREDENTIALS,src=gcloud_credentials \
              -t $image_id .

      # Clean up: Remove IP from whitelist
      - name: Disable Github worker IP
        uses: Mariolaus/open_actions/.github/actions/delete_worker_ip@main
        if: always()
        with:
          github_id: "${{ steps.add_ip.outputs.github_id }}"
          credentials_json: '${{ secrets.GCP_BUILD_AND_DEPLOY_PROD }}'
          url: "${{ inputs.action_url }}/delete_ip?github_id="
